# Generated by Django 6.0.3 on 2026-03-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
