# Generated by Django 6.0.3 on 2026-03-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_menu_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='discount_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menu',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
